version: '2'

services:
  web:
      image: nginx:stable
      ports:
        - "80:80"
      volumes_from:
        - master
      volumes:
        # - ./opus:/var/www/html
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
  php:
      image: phillaf/php-mysql
      volumes_from:
        - master
      volumes:
        # - ./opus:/var/www/html
        - ./opus-master/conf/php.ini:/usr/local/etc/php/conf.d/custom.ini
        - ./opus-master/conf/opus.env:/var/www/html/.env
  master:
    build: opus-master
    image: opus-master
  redis:
      image: redis:latest
  db:
    image: mysql:latest
    environment:
      - MYSQL_ONETIME_PASSWORD=yes
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=opus
      - MYSQL_USER=uzmantech
      - MYSQL_PASSWORD=opus-wiki-on-docker
  migration:
    image: opus-master
    command: php artisan migrate
    depends_on:
      - db
  key:
    image: opus-master
    command: php artisan key:generate
    depends_on:
      - db
      - migration
  db-seed:
    image: opus-master
    command: php artisan db:seed
    depends_on:
      - db
      - migration
      - key
